NAME: 'sade_config'
OUTPUT_DIR: 'output/imagenet_lt/x50'
SHOW_STEP: 200
SAVE_STEP: 10
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'
RESUME_MODEL: 'tmp/epoch_150.pth'


DATASET:
  DATASET: 'ImageNet_LT'
  TRAIN_JSON: 'dataset_json/ImageNet_LT_train.json'
  VALID_JSON: 'dataset_json/ImageNet_LT_val.json'

BACKBONE:
  TYPE: 'resnext50'
  MULTI_NETWORK_TYPE: ['resnext50','resnext50','resnext50']
MODULE:
  TYPE: 'GAP'

DROPOUT: False

CLASSIFIER:
  TYPE: 'cos'
  SEMI_TYPE: 'mlp'
  BIAS: True

LOSS:
  LOSS_TYPE: 'NIL_NBOD'
  MULTI_CLASIIFIER_LOSS:
    DIVERSITY_FACTOR: 0.6
    DIVERSITY_FACTOR_HCM: 0.6
  HCM_N: 300
  HCM_RATIO: 1.0
  CE_RATIO: 1.0
  CON_RATIO: 0.0
TRAIN:
  BATCH_SIZE: 64
  MAX_EPOCH: 180
  NUM_WORKERS: 8
  COMBINER:
    TYPE: 'multi_network_default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.025
    MOMENTUM: 0.9
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'cosine'
    COSINE_DECAY_END: 180
    ETA_MIN: 0.0
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    MULTI_NETWORK_TYPE: ['default']

  DISTRIBUTED: True
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip", "color_jitter")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 512
  NUM_WORKERS: 16
  MODEL_FILE: 'best_model.pth'